version: '3'

networks:
  laravel:
volumes:
  mysql8-data:
services:
  site:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:delegated #
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - redis
      - mysql
    networks:
      - laravel

  mysql:
    image: mariadb:10.4
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  mysql8:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql8
    restart: unless-stopped
    tty: true
    ports:
      - 3308:3306
    volumes:
      - mysql8-data:/var/lib/mysql
      - ./mysql8/config:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql8
    networks:
      - laravel
  php:
    build:
      context: ./dockerfiles
      dockerfile: php8.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - laravel

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel
#  npm:
#    image: node:13.7
#    container_name: npm
#    volumes:
#      - ./src:/var/www/html
#    ports:
#      - 3000:3000
#      - 3001:3001
#    working_dir: /var/www/html
#    entrypoint: ['npm']
#    networks:
#      - laravel

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: artisan.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - INSTALL_BEAST=true
    container_name: artisan
    volumes:
      - ./src:/var/www/html:delegated
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
      

